# Generated by Django 2.2.5 on 2019-09-22 15:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network_app', '0001_adding_CustomUser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='friends',
            field=models.ManyToManyField(related_name='_customuser_friends_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
