# Generated by Django 2.2.5 on 2019-09-30 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network_app', '0003_added_Post_and_Comment_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-datetime_posted']},
        ),
        migrations.AddField(
            model_name='customuser',
            name='cover_picture',
            field=models.URLField(default='https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&fit=crop&ixid=eyJhcHBfaWQiOjF9', max_length=400),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.URLField(default='https://source.unsplash.com/featured/?{happy, human, face, adult}', max_length=400),
        ),
    ]
