# Generated by Django 2.2.5 on 2019-10-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network_app', '0004_added_url_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cover_picture',
            field=models.URLField(max_length=400),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.URLField(max_length=400),
        ),
    ]
